spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: report_service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/postgres
    username: task_manager
    password: root
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd
    time-zone: GMT+3

jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: ITAcademy
feign:
  audit:
    url: http://audit-service:8080/out
server:
  port: 8080
minio:
  bucket: audit-report
  url: http://minio:9000
  accessKey: minioadmin
  secretKey: minioadmin